### ISSUE TITLE
"ValueError: Col and row must be greater than zero" when parsing member variable comments or c++ attributes

### ISSUE THREAD

**Issue by TrevorCash** [JhnW/devana#11]
Hi JhnW, 

I have been parsing some headers and listing member variables inside of classes.

I can use the following code to print the names of all member variables:

```
 memberVariables = filter(lambda f: isinstance(f, FieldInfo), source_class.content)


for m in memberVariables:
    print(m)
    a = f"c.{m.name}"
    #for att in m.flatten_attributes:
    #    print(att)
    #print(m.associated_comment)

```

which works fine and prints out all the FieldInfo objects.

When I try: print(m.associated_comment) however I get a bunch of None types (which makes sense because its optional).

but then on a particular member function - I get this stack error:

```
FieldInfo:peepSpawnQueue (<devana.syntax_abstraction.classinfo.FieldInfo object at 0x000001DF8736F550>)
Traceback (most recent call last):
  File "C:\Users\casht\repos\netgame2\CodeGeneration\updateSerializationCode.py", line 177, in <module>
    updateSerializations(fileList)
  File "C:\Users\casht\repos\netgame2\CodeGeneration\updateSerializationCode.py", line 123, in updateSerializations
    serialization_method = create_class_serializer_code(e)
  File "C:\Users\casht\repos\netgame2\CodeGeneration\updateSerializationCode.py", line 63, in create_class_serializer_code
    print(m.associated_comment)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\utility\lazy.py", line 21, in wrapper
    return func(self)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\classinfo.py", line 416, in associated_comment
    self._associated_comment = parent.bind_comment(self)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\organizers\sourcefile.py", line 343, in bind_comment
    return self._comments_factory.get_upper_comment(element.text_source)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\comment.py", line 158, in get_upper_comment
    line = element.begin.row
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\utility\lazy.py", line 21, in wrapper
    return func(self)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\codepiece.py", line 52, in begin
    self._begin = CodeLocation(self._cursor.extent.start.line, self._cursor.extent.start.column)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\codelocation.py", line 6, in __init__
    raise ValueError(f"Col and row must be greater than zero. r:{row},c:{col}")
ValueError: Col and row must be greater than zero. r:0,c:0
```

peepSpawnQueue looks like this:

```
class GameState : public GE::GameState {
public:

	void Serialize(std::ostream* stream) override;
	void DeSerialize(std::istream* stream) override;

	SynchronizedClientState clientStates[MAX_CLIENTS];
	ge_int numClients;

	std::vector<Peep> peeps;
	ge_offsetPtr nextFreePeepPtr;
	std::vector<PeepSpawn> peepSpawnQueue[GAME_UPDATE_WORKITEMS];
	

        ...
```

where GAME_UPDATE_WORKITEMS is a const int.

This same error comes up when I try printing c++ attributes as well.

Any help appreciated, Thanks!

-Trevor

**Comment by JhnW** [comment]
Hi @TrevorCash. It looks interesting. I will try to reproduce this case. If I have problems, I will contact you with a request for a minimal example, but don't worry about it for now.

**Comment by JhnW** [comment]
The problem was (I hope this is the only problem that caused your code to fail) parsing the details for TypeExpression when the type is array. When I wrote this feature, I did not add a test for details, and at the same time I forgot to add logic for array. As a result, type modification information was parsed, but not its exact information.

@TrevorCash 
I've just pushed version 2.2.1 with a fix to pypi. Please check if this solves your problems.

**Comment by TrevorCash** [comment]
Hi @JhnW ,  I still am getting the same "ValueError: Col and row must be greater than zero." error with same stack trace.

The error still occurs when parsing the peepSpawnQueue array.

**Comment by TrevorCash** [comment]
Attached is the test case (run "python updateSerializationCode.py " from inside the CodeGeneration folder.
[devanatestcase.zip](https://github.com/JhnW/devana/files/13244695/devanatestcase.zip)

For me it gives this output:

```
python updateSerializationCode.py 
Updating Serializers
SourceFile:SourceFileType.HEADER:Game.h (<devana.syntax_abstraction.organizers.sourcefile.SourceFile object at 0x00000244494B15A0>)
diagnostics for SourceFile:SourceFileType.HEADER:Game.h (<devana.syntax_abstraction.organizers.sourcefile.SourceFile object at 0x00000244494B15A0>) is [<Diagnostic severi
ty 4, location <SourceLocation file '../Engine\\Game.h', line 8, column 10>, spelling "'GE.Basic.h' file not found">]
parsing source class: PeepState_Basic
FieldInfo:bitflags0 (<devana.syntax_abstraction.classinfo.FieldInfo object at 0x0000024449502DD0>)
None
FieldInfo:faction (<devana.syntax_abstraction.classinfo.FieldInfo object at 0x0000024449502E00>)
None
FieldInfo:health (<devana.syntax_abstraction.classinfo.FieldInfo object at 0x0000024449502E30>)
None
FieldInfo:deathState (<devana.syntax_abstraction.classinfo.FieldInfo object at 0x0000024449502E60>)
None
FieldInfo:orderPtrStack (<devana.syntax_abstraction.classinfo.FieldInfo object at 0x0000024449502E90>)
Traceback (most recent call last):
  File "C:\Users\casht\repos\devanatestcase\CodeGeneration\updateSerializationCode.py", line 149, in <module>
    updateSerializations(fileList)
  File "C:\Users\casht\repos\devanatestcase\CodeGeneration\updateSerializationCode.py", line 127, in updateSerializations
    serialization_method = create_class_serializer_code(e)
  File "C:\Users\casht\repos\devanatestcase\CodeGeneration\updateSerializationCode.py", line 61, in create_class_serializer_code
    print(m.associated_comment)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\utility\lazy.py", line 21, in wrapper
    return func(self)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\classinfo.py", line 416, in associated_comment
    self._associated_comment = parent.bind_comment(self)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\organizers\sourcefile.py", line 343, in bind_comment
    return self._comments_factory.get_upper_comment(element.text_source)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\comment.py", line 158, in get_upper_comment
    line = element.begin.row
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\utility\lazy.py", line 21, in wrapper
    return func(self)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\codepiece.py", line 52, in begin
    self._begin = CodeLocation(self._cursor.extent.start.line, self._cursor.extent.start.column)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python310\lib\site-packages\devana\syntax_abstraction\codelocation.py", line 6, in __init__
    raise ValueError("Col and row must be greater than zero.")
ValueError: Col and row must be greater than zero.



```

**Comment by TrevorCash** [comment]
Attached is also a version with more supporting headers included [devanatestcase_larger.zip](https://github.com/JhnW/devana/files/13244760/devanatestcase_larger.zip)

**Comment by TrevorCash** [comment]
I have found (using devanatestcase_larger.zip) that line 697 in Game.h gives the error:

`std::vector<PeepSpawn> peepSpawnQueue[GAME_UPDATE_WORKITEMS];`

but if changed to:

`int peepSpawnQueue[GAME_UPDATE_WORKITEMS];`

It then works.

changing to 

`std::vector<int> peepSpawnQueue[GAME_UPDATE_WORKITEMS];`

also fails.

**Comment by JhnW** [comment]
Hi @TrevorCash 
I think I found the source of your problem. In fact, these are even two potential problems.
- You use C++20 features such as concepts. Be warned that devana does not support them. As long as you don't ask for concept data, and it only exists next to the code you're working with, everything should be fine. However, you need to set the module configuration to C++20 for it to work: 
```
cfg = Configuration()
cfg.parsing.language_version = LanguageStandard.CPP_20
source = SourceModule("API", "../Engine", module_filter, configuration = cfg)
```
- As I see, you are using https://github.com/kthohr/gcem. Ok, but you need to have headers provided to devana (like compilers do it). Please check https://jhnw.github.io/devana/api/devana.html#devana.configuration.ParsingConfiguration. You need provide path to headers if it is outside module directory. 

**Currently your parsing is broken from clang's point of view.**

Please check diagnostics errors.
Maybe in the future I should add diagnostic filtering and throwing an appropriate exception to the restrictive mode. Sounds like a good idea.

Bonus:

- Devana don't like defines in parsed headers.
- Devana may not see difference between struct and c-tyle struct with typedef, maybe will not parse it. I have plan to handle it in future.

**Comment by TrevorCash** [comment]
Hi @JhnW ,

Thanks for the tips.

I have updated to specify CPP_20 in the configuration and added all header paths to the configuration using IncludeSet.

So now diagnostics does not give missing header errors.

Indeed - now it throws errors about template constraints.
`diagnostics for SourceFile:SourceFileType.HEADER:GE.Basic.Types.Basic.h (<devana.syntax_abstraction.organizers.sourcefile.SourceFile object at 0x00000264C3C36620>) is [<Diagnostic 
severity 3, location <SourceLocation file '../Engine\\GE.Basic.Types.Basic.h', line 703, column 10>, spelling "use of undeclared identifier 'GE2_TYPE_CONSTRAINT'">]`

I am happy with ignoring these for now if there is a way around it.

**Comment by JhnW** [comment]
@TrevorCash 
Concepts and modules are some of the main C++20 features that are not currently supported by Devan. You just shouldn't use them at the moment. Devana's backend is able to handle them, so we don't have any problems at the beginning. 
Don't use mean:
File bar.hpp:
`
#include "foo.hpp" //header with concepts
//here you code without concepts 
`
All works fine in bar.hpp. You can use concept-based templates in function body.

File bar.hpp:
`
struct Foo
{

};

Concept X

struct Bar
{
//field with concept
}
`
In this case you can touch Foo, but not X (include file.conent) and touch Bar care to skip concept field. Rememer that a lot of functions like name may touch whole conent.

As for future work, first of all I would like to finish the code generation framework (a higher layer on code printers), it is a lot of work. After that, only C++20 is in the queue. Concepts will most likely be supported faster than modules because with the latter I'm still waiting for the C++ community to develop some well-known standards that I will follow.
However, adding concept support is also a big task. Generally, clang's parser adds a lot of clutter around the template, losing some parameters, etc. Here, devan has the opportunity to prove itself (you can see in the sources how wildly I have to choose specializations). I'll probably have a lot of fun with the concepts.

**Comment by TrevorCash** [comment]
@JhnW 
Ok - I will probably refactor my headers a bit and/or add some simple pre-processing to remove concepts code from files given to Devana.


-Thanks for the help

**Comment by TrevorCash** [comment]
To Follow up - I was able to get parsing working without errors, by spliting my headers up so Devana only processes header code without concepts.  comments and attributes are working now
